### ISSUE TITLE
if Backends is empty, the proxy will be panic

### ISSUE THREAD

**Issue by ybping** [xsank/EasyProxy#1]
panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x5b9d29 pc=0x5b9d29]

goroutine 9 [running]:
panic(0x7c8020, 0xc82000a0f0)
	/usr/lib/golang/src/runtime/panic.go:481 +0x3e6
github.com/xsank/EasyProxy/src/proxy/schedule.(*Poll).Choose(0xc82000b260, 0xc82000bfd0, 0xf, 0xa7ce70, 0x0, 0x0, 0xc8200118c0, 0xc820011800)
	/vagrant/.gopath/src/github.com/xsank/EasyProxy/src/proxy/schedule/poll.go:12 +0x49
github.com/xsank/EasyProxy/src/proxy.(*EasyProxy).Dispatch(0xc8200aca00, 0x7f00e89faa70, 0xc820022088)
	/vagrant/.gopath/src/github.com/xsank/EasyProxy/src/proxy/esay_proxy.go:64 +0x11c
created by github.com/xsank/EasyProxy/src/gateway.(*ProxyServer).Start
	/vagrant/.gopath/src/github.com/xsank/EasyProxy/src/gateway/server.go:46 +0x3ed
exit status 2

**Comment by xsank** [comment]
@ybping ,now it fixed, thank you for your information

**Comment by ybping** [comment]
@xsank isBackendAvailable may not work, because `backends` is critical resources.  I refine your code, pls refer PR.

**Comment by xsank** [comment]
it fix the apparent logic bug, but there maybe still exist some critical resources problem,  i will use a better way to solve this. thanks again~
