### ISSUE TITLE
Fix govet golint warnings

### ISSUE THREAD

**Issue by ybping** [xsank/EasyProxy#4]
TODO:
1. fix govet warnings
2. fix golint warnings

**Comment by xsank** [comment]
i have thought about the makefile, but i hope that the proxy could be built on windows. so i use the build.go to build and it works. but i still do not find a good way to solve the command feature like rm<->rmdir, cp <-> copy

**Comment by ybping** [comment]
Maybe we can define alias cmds based on different os type

**Comment by xsank** [comment]
@ybping ，we can use system call, now finished.
