### ISSUE TITLE
Multi-threads safety

### ISSUE THREAD

**Issue by chrislee87** [xsank/EasyProxy#5]
Both ChannelManager and ProxyData are multi-threads unsafe, so why not protect those append or delete operations to the same slice or map from different goroutines with sync.Mutex?

**Comment by xsank** [comment]
Yes, i have noticed that and will fix this on this weekend, still have a lot company work to do on day. Orz...

**Comment by chrislee87** [comment]
Struct anonymous embedding may solve this problem.
**_type ProxyData struct {
	Service        string
	Host           string
	Port           uint16
	Backends       map[string]structure.Backend
	Deads          map[string]structure.Backend
	ChannelManager *structure.ChannelManager
        sync.RWMutex
}_**

 Not forget _**type Poll struct**_.

**Comment by xsank** [comment]
@chrislee87  ,add mutex can solve the problem exactly, but i do not like lock exist here and there,  channel or concurrent map maybe a choice , i am still considering about this.

**Comment by xsank** [comment]
@chrislee87 ,i have to say that mutex is the easiest way but looks like a little dirty.

**Comment by chrislee87** [comment]
Yes, using mutex here is a little dirty. Looking forward to your solution.
