### ISSUE TITLE
svn协议连接异常

### ISSUE THREAD

**Issue by koujun2012** [xsank/EasyProxy#6]
我是用这个来代理连接到svn服务器，比如svn://localhost:9999,启动proxy后，连接不过去，后台还保持了好几个连接到背后的svn服务器，可能是我通过9999端口访问的时候关掉了，
1.但是proxy与svn之间的连接没断开。
2.ctrl+c 关不掉程序
3.svn协议的不行？

**Comment by xsank** [comment]
1.localhost改成127.0.0.1试试，看下statistic页面中的连接情况
2.ctrl+c关不掉，机子是windows吗？
3.测试过mysql和ssh，svn的这个今晚我弄个环境看看

**Comment by koujun2012** [comment]
1.本来是127.0.0.1，改成0.0.0.0以后可以了，因为是外网访问的。
2.ctrl+c关不掉还是存在，是centos6
3.背后创建8个线程去连接 ，在哪里可以配呀

**Comment by koujun2012** [comment]
![image](https://cloud.githubusercontent.com/assets/1762715/20824751/2ab920de-b89a-11e6-9892-fb722447a7c5.png)
1G内存，1核的阿里云服务器 貌似比较耗资源

**Comment by xsank** [comment]
1.本地测试是连接127.0.0.1比较稳妥，localhost有时候会出现ip对应不上
2.ctrl+c这个问题今天晚上搞环境修
3.因为代理程序本身是IO密集型的，所以GOMAXPROCS设置为了两倍runtime cpu，这个在main.go中可以修改
感谢提供的信息，今天晚上跟进修复~

**Comment by xsank** [comment]
@koujun2012 ，问题已经修复，另外现在heartbeat的时间和procnum都是可配置的
